= AMQ Broker Leader Leader-Follower deployments that use a shared journal 
  
== Chapters:

Environment Setup:

- Red Hat Integration - AMQ Broker for RHEL 9 (Multiarch) : 7.13.0-opr-1 provided by Red Hat

Prerequisites:

- Install AMQ Broker Operator:  from OperatorHub

=== 1. Setting Up Initial Environment

Create the 'activemq' namespace: `oc new-project activemq`

Create the PVC where the shared Mount will hosted:
  
[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume
  namespace: activemq
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
EOF
----

NOTE: The PVC status will be `Pending` until the deployment of the broker to bound that volume.

[source, yaml,indent=0]
----
oc get pvc
NAME            STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
shared-volume   Pending                                      gp3-csi        <unset>                 7s
----

Create two AMQ Brokers `peer-broker-a` and `peer-broker-b` in the namespace `activemq` using the following activemqArtemis CRs YAML configuration:

[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: peer-broker-a
spec:
  brokerProperties:
  - HAPolicyConfiguration=SHARED_STORE_PRIMARY
  - journalDirectory=/opt/amq-broker/data/journal
  - pagingDirectory=/opt/amq-broker/data/paging,
  - bindingsDirectory=/opt/amq-broker/data/bindings
  - largeMessagesDirectory=/opt/amq-broker/data/largemessages
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    clustered: false
    extraVolumes:
    - name: extra-volume
      persistentVolumeClaim:
        claimName: shared-volume
    extraVolumeMounts:
    - name: extra-volume
      mountPath: /opt/amq-broker/data
  livenessProbe:
    exec:
      command:
      - test
      - -f
      - /home/jboss/amq-broker/lock/cli.lock
EOF
---
oc apply -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: peer-broker-b
spec:
  brokerProperties:
  - HAPolicyConfiguration=SHARED_STORE_PRIMARY
  - journalDirectory=/opt/amq-broker/data/journal
  - pagingDirectory=/opt/amq-broker/data/paging,
  - bindingsDirectory=/opt/amq-broker/data/bindings
  - largeMessagesDirectory=/opt/amq-broker/data/largemessages
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    clustered: false
    extraVolumes:
    - name: extra-volume
      persistentVolumeClaim:
        claimName: shared-volume
    extraVolumeMounts:
    - name: extra-volume
      mountPath: /opt/amq-broker/data
  livenessProbe:
    exec:
      command:
      - test
      - -f
      - /home/jboss/amq-broker/lock/cli.lock
EOF
----

NOTE: The logs will show specific lines that indicate the `leader` and `follower`:

[source, yaml,indent=0]
----
#peer-broker-a-ss-0
INFO  [org.apache.activemq.artemis.core.server] AMQ221034: Waiting indefinitely to obtain primary lock
INFO  [org.apache.activemq.artemis.core.server] AMQ221035: Primary Server Obtained primary lock
INFO  [org.apache.activemq.artemis.core.server] AMQ221080: Deploying address DLQ supporting [ANYCAST]

#peer-broker-b-ss-0
INFO  [org.apache.activemq.artemis.core.server] AMQ221034: Waiting indefinitely to obtain primary lock
----

[source, yaml,indent=0]
----
oc get pods -n activemq
NAME                 READY   STATUS             RESTARTS         AGE
peer-broker-a-ss-0   1/1     Running            0                72m
peer-broker-b-ss-0   0/1     Running            27 (3m36s ago)   72m
----

Create a service object `ext-acceptor-svc` in the namespace `oracle-jdbc-shared-store` that regroups both AMQ Broker Pods `peer-broker-a-ss-0` and `peer-broker-b-ss-0` using the selector `peer.group: jdbc-ha`:

[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: v1
kind: Service
metadata: 
  name: ext-acceptor-svc
spec:
  ports:
    - protocol: TCP
      port: 61626
      targetPort: 61626
  selector:
    peer.group: jdbc-ha
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ext-acceptor-svc-rte
spec:
  port:
    targetPort: 61626
  tls:
    termination: passthrough 
    insecureEdgeTerminationPolicy: None 
  to:
    kind: Service
    name: ext-acceptor-svc
EOF
----

=== 2. Test the Failover

[source, yaml,indent=0]
----
export EXT_ACCEPTOR_HOST=$(oc get route ext-acceptor-svc-rte -o json | jq -r '.spec.host')

## Producer
/apache-artemis-2.28.0.redhat-00019/bin/artemis producer --verbose --destination queue://TEST --user admin --password admin --protocol core --sleep 1000 --url "tcp://${EXT_ACCEPTOR_HOST}:443?sslEnabled=true&verifyHost=false&trustStorePath=server-ca-truststore.jks&trustStorePassword=securepass&useTopologyForLoadBalancing=false&initialConnectAttempts=-1&failoverAttempts=-1"

## COnsumer
/apache-artemis-2.28.0.redhat-00019/bin/artemis consumer --verbose --destination queue://TEST --user admin --password admin --protocol core --sleep 1000 --url "tcp://${EXT_ACCEPTOR_HOST}:443?sslEnabled=true&verifyHost=false&trustStorePath=server-ca-truststore.jks&trustStorePassword=securepass&useTopologyForLoadBalancing=false&initialConnectAttempts=-1&failoverAttempts=-1"
----

=== 3. Setup the Mirroring for DR env.

- DR Env:

Create the 'DR' namespace: `oc new-project dr`

Create AMQ Broker using activemqArtemis CR YAML configuration

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
 name: broker-dr
 namespace: dr
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
      protocols: all
      sslEnabled: false
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
      sslEnabled: false
  adminPassword: admin
  adminUser: admin
  brokerProperties:
    - maxDiskUsage=85
    - clusterConfigurations.my-cluster.producerWindowSize=-1
    - 'addressSettings.#.redeliveryMultiplier=5'
    - criticalAnalyzer=true
    - criticalAnalyzerTimeout=6000
    - criticalAnalyzerCheckPeriod=-1     
    - criticalAnalyzerPolicy=LOG
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: true
    image: placeholder
EOF
----

Setup `Mirroring` using `brokerProperties` on the two AMQ Brokers `peer-broker-a` and `peer-broker-b` in the namespace `oracle-jdbc-shared-store` namespace: `oc project oracle-jdbc-shared-store`:

[source, yaml,indent=0]
----
    - >-
      AMQPConnections.dr.uri=tcp://broker-dr-all-0-svc.dr.svc.cluster.local:61616
    - AMQPConnections.dr.retryInterval=5000
    - AMQPConnections.dr.user=admin
    - AMQPConnections.dr.password=admin
    - AMQPConnections.dr.connectionElements.mirror.type=MIRROR
    - >-
      AMQPConnections.dr.connectionElements.mirror.messageAcknowledgements=true
    - AMQPConnections.dr.connectionElements.mirror.queueCreation=true
    - AMQPConnections.dr.connectionElements.mirror.queueRemoval=true
----

==== 7.1 Mirror Events:

Locate the `leader` pod using `oc get pods`:

[source, yaml,indent=0]
----
oc get pods
NAME                 READY   STATUS    RESTARTS   AGE
peer-broker-a-ss-0   0/1     Running   0          86s
peer-broker-b-ss-0   1/1     Running   0          87s
----

1.Event: Creating Address:

[source, yaml,indent=0]
----
export POD=peer-broker-b-ss-0
oc exec -n oracle-jdbc-shared-store -i $POD -- /home/jboss/amq-broker/bin/artemis address create --acceptor all --anycast --no-multicast --name fr.nantes --user admin --password admin 
----

2.Event: Creating Queue:

[source, yaml,indent=0]
----
export POD=peer-broker-b-ss-0
oc exec -n oracle-jdbc-shared-store -i $POD -- /home/jboss/amq-broker/bin/artemis queue create --name fr.nantes --address fr.nantes --anycast --durable --user admin --password admin --acceptor all --silent
----

3.Event Producing Messages:

[source, yaml,indent=0]
----
export POD=peer-broker-b-ss-0
oc exec -n oracle-jdbc-shared-store -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://fr.nantes --user admin --password admin --message-count 1 --message 1 
----

Check on the DR env:

[source, yaml,indent=0]
----
export POD=broker-dr-ss-0
oc exec -n dr -i $POD -- /home/jboss/amq-broker/bin/artemis address show --acceptor all --user admin --password admin
oc exec -n dr -i $POD -- /home/jboss/amq-broker/bin/artemis queue stat --acceptor all --user admin --password admin
----

Delete the leader in order to failover 

[source, yaml,indent=0]
----
oc delete pods peer-broker-b-ss-0
pod "peer-broker-b-ss-0" deleted
oc get pods
NAME                 READY   STATUS    RESTARTS   AGE
peer-broker-a-ss-0   1/1     Running   0          5m51s
peer-broker-b-ss-0   0/1     Running   0          5s
----

3.Event Producing Messages:

[source, yaml,indent=0]
----
export POD=peer-broker-a-ss-0
oc exec -n oracle-jdbc-shared-store -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://fr.nantes --user admin --password admin --message-count 1 --message 1 
----

Check on the DR env:

[source, yaml,indent=0]
----
export POD=broker-dr-ss-0
oc exec -n dr -i $POD -- /home/jboss/amq-broker/bin/artemis address show --acceptor all --user admin --password admin
oc exec -n dr -i $POD -- /home/jboss/amq-broker/bin/artemis queue stat --acceptor all --user admin --password admin
----

You should have `two messages` in the queue `fr.nantes`, like:

[source, yaml,indent=0]
----
Connection brokerURL = tcp://broker-dr-ss-0.broker-dr-hdls-svc.dr.svc.cluster.local:61616
|NAME              |ADDRESS           |CONSUMER|MESSAGE|MESSAGES|DELIVERING|MESSAGES|SCHEDULED|ROUTING|INTERNAL|
|                  |                  | COUNT  | COUNT | ADDED  |  COUNT   | ACKED  |  COUNT  | TYPE  |        |
|$sys.mqtt.sessions|$sys.mqtt.sessions|   0    |   0   |   0    |    0     |   0    |    0    |ANYCAST|  true  |
|DLQ               |DLQ               |   0    |   0   |   0    |    0     |   0    |    0    |ANYCAST| false  |
|ExpiryQueue       |ExpiryQueue       |   0    |   0   |   0    |    0     |   0    |    0    |ANYCAST| false  |
|fr.nantes         |fr.nantes         |   0    |   2   |   2    |    0     |   0    |    0    |ANYCAST| false  |
----
