= AMQ Broker Leader Leader-Follower deployments that use a shared journal 
  
== Chapters:

Environment Setup:

- Red Hat Integration - AMQ Broker for RHEL 9 (Multiarch) : 7.13.0-opr-1 provided by Red Hat

Prerequisites:

- Install AMQ Broker Operator:  from OperatorHub

=== 1. Setting Up Initial Environment

Create the 'activemq' namespace: `oc new-project activemq`

Create the PVC where the shared Mount will hosted:
  
[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume
  namespace: activemq
spec:
  accessModes:
# It must be - ReadWriteMany, please do the change
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
EOF
----

NOTE: The PVC status will be `Pending` until the deployment of the broker to bound that volume.

[source, yaml,indent=0]
----
oc get pvc
NAME            STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
shared-volume   Pending                                      gp3-csi        <unset>                 7s
----

Create the secret `ext-acceptor-ssl-secret` for one-way TLS:
  
[source, yaml,indent=0]
----
wget -O server-keystore.jks https://github.com/apache/activemq-artemis/raw/main/tests/security-resources/server-keystore.jks
wget -O server-ca-truststore.jks https://github.com/apache/activemq-artemis/raw/main/tests/security-resources/server-ca-truststore.jks
wget -O client-ca-truststore.jks https://github.com/apache/activemq-artemis/raw/main/tests/security-resources/client-ca-truststore.jks
oc create secret generic ext-acceptor-ssl-secret \
--from-file=broker.ks=server-keystore.jks \
--from-file=client.ts=client-ca-truststore.jks \
--from-literal=keyStorePassword=securepass \
--from-literal=trustStorePassword=securepass
----


Create two AMQ Brokers `peer-broker-a` and `peer-broker-b` in the namespace `activemq` using the following activemqArtemis CRs YAML configuration:

[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: peer-broker-a
spec:
  brokerProperties:
  - HAPolicyConfiguration=SHARED_STORE_PRIMARY
  - journalDirectory=/opt/amq-broker/data/journal
  - pagingDirectory=/opt/amq-broker/data/paging,
  - bindingsDirectory=/opt/amq-broker/data/bindings
  - largeMessagesDirectory=/opt/amq-broker/data/largemessages
  acceptors:
  - name: ext-acceptor
    protocols: CORE
    port: 61626
    expose: true
    sslEnabled: true
    sslSecret: ext-acceptor-ssl-secret
  console:
    expose: true
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    livenessProbe:
      exec:
        command:
        - test
        - -f
        - /home/jboss/amq-broker/lock/cli.lock
    labels:
      peer.group: peer-broker
    size: 1
    persistenceEnabled: false
    clustered: false
    extraVolumes:
    - name: extra-volume
      persistentVolumeClaim:
        claimName: shared-volume
    extraVolumeMounts:
    - name: extra-volume
      mountPath: /opt/amq-broker/data
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: peer-broker-b
spec:
  brokerProperties:
  - HAPolicyConfiguration=SHARED_STORE_PRIMARY
  - journalDirectory=/opt/amq-broker/data/journal
  - pagingDirectory=/opt/amq-broker/data/paging,
  - bindingsDirectory=/opt/amq-broker/data/bindings
  - largeMessagesDirectory=/opt/amq-broker/data/largemessages
  acceptors:
  - name: ext-acceptor
    protocols: CORE
    port: 61626
    expose: true
    sslEnabled: true
    sslSecret: ext-acceptor-ssl-secret
  console:
    expose: true
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    livenessProbe:
      exec:
        command:
        - test
        - -f
        - /home/jboss/amq-broker/lock/cli.lock
    labels:
      peer.group: peer-broker
    size: 1
    persistenceEnabled: false
    clustered: false
    extraVolumes:
    - name: extra-volume
      persistentVolumeClaim:
        claimName: shared-volume
    extraVolumeMounts:
    - name: extra-volume
      mountPath: /opt/amq-broker/data
EOF
----

NOTE: The logs will show specific lines that indicate the `leader` and `follower`:

[source, yaml,indent=0]
----
#peer-broker-a-ss-0
INFO  [org.apache.activemq.artemis.core.server] AMQ221034: Waiting indefinitely to obtain primary lock
INFO  [org.apache.activemq.artemis.core.server] AMQ221035: Primary Server Obtained primary lock
INFO  [org.apache.activemq.artemis.core.server] AMQ221080: Deploying address DLQ supporting [ANYCAST]

#peer-broker-b-ss-0
INFO  [org.apache.activemq.artemis.core.server] AMQ221034: Waiting indefinitely to obtain primary lock
----

[source, yaml,indent=0]
----
oc get pods -n activemq
NAME                 READY   STATUS             RESTARTS         AGE
peer-broker-a-ss-0   1/1     Running            0                72m
peer-broker-b-ss-0   0/1     Running            27 (3m36s ago)   72m
----

Create a service object `ext-acceptor-svc` in the namespace `activemq` that regroups both AMQ Broker Pods `peer-broker-a-ss-0` and `peer-broker-b-ss-0` using the selector `peer.group: peer-broker`:

[source, yaml,indent=0]
----
oc apply -f - <<EOF
apiVersion: v1
kind: Service
metadata: 
  name: ext-acceptor-svc
spec:
  ports:
    - protocol: TCP
      port: 61626
      targetPort: 61626
  selector:
    peer.group: peer-broker
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ext-acceptor-svc-rte
spec:
  port:
    targetPort: 61626
  tls:
    termination: passthrough 
    insecureEdgeTerminationPolicy: None 
  to:
    kind: Service
    name: ext-acceptor-svc
EOF
----

=== 2. Test the Failover

[source, yaml,indent=0]
----
export EXT_ACCEPTOR_HOST=$(oc get route ext-acceptor-svc-rte -o json | jq -r '.spec.host')

## Producer
bin/artemis producer --verbose --destination queue://TEST --user admin --password admin --protocol core --sleep 1000 --url "tcp://${EXT_ACCEPTOR_HOST}:443?sslEnabled=true&verifyHost=false&trustStorePath=client-ca-truststore.jks&trustStorePassword=securepass&useTopologyForLoadBalancing=false&initialConnectAttempts=-1&failoverAttempts=-1"

## Consumer
bin/artemis consumer --verbose --destination queue://TEST --user admin --password admin --protocol core --sleep 1000 --url "tcp://${EXT_ACCEPTOR_HOST}:443?sslEnabled=true&verifyHost=false&trustStorePath=client-ca-truststore.jks&trustStorePassword=securepass&useTopologyForLoadBalancing=false&initialConnectAttempts=-1&failoverAttempts=-1"
----
