= Deploying AMQ Broker Secured with JAAS Properties LoginModule

This tutorial provides a step-by-step guide to securing an Red Hat Integration - AMQ Broker deployment using the **JAAS Properties LoginModule**. This method allows you to manage authentication and authorization through property files stored as Kubernetes Secrets.

== Environment Setup
* **Model:** Red Hat Integration - AMQ Broker for RHEL 8 (Multiarch)
* **Version:** 7.13.3-opr-1
* **Prerequisites:** AMQ Broker Operator must be installed via OperatorHub.

== 1. Prepare the Configuration Workspace
First, create a local temporary directory to manage your configuration files before uploading them to the cluster.

[source,bash]
----
mkdir tmp-jaas
cd tmp-jaas
----

== 2. Define the JAAS Login Configuration
Create the `login.config` file. This defines how the broker validates credentials. We use two modules: one for custom application users and one for default system users.

[source,bash]
----
cat <<"EOF" > login.config
activemq {
   org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
      reload=true
      org.apache.activemq.jaas.properties.user="new-users.properties"
      org.apache.activemq.jaas.properties.role="new-roles.properties";

   org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
      reload=false
      org.apache.activemq.jaas.properties.user="artemis-users.properties"
      org.apache.activemq.jaas.properties.role="artemis-roles.properties"
      baseDir="/home/jboss/amq-broker/etc";
};
EOF
----

[TIP]
====
Setting the flag to `sufficient` ensures that if a user is found in the first module, authentication succeeds immediately. If not, it falls back to the second module.
====

== 3. Configure Users and Roles
Define your security identities in the following property files.

.Create Users (username=password)
[source,bash]
----
cat <<"EOF" > new-users.properties
ruben=ruben
rick=rick
batch=batch
EOF
----

.Create Roles (role=user_list)
[source,bash]
----
cat <<"EOF" > new-roles.properties
admin=ruben, rick
viewer=batch
EOF
----

== 4. Create the Kubernetes Secret
Store these configuration files in an OpenShift secret. This secret will be mounted by the Broker Pods.

[source,bash]
----
oc create secret generic custom-jaas-config \
  --from-file=login.config \
  --from-file=new-users.properties \
  --from-file=new-roles.properties
----

== 5. Deploy the AMQ Broker
Apply the Custom Resource to trigger the deployment via the Operator.

[source,bash]
----
oc apply -f https://raw.githubusercontent.com/aboucham/activemq-artemis-tutorials/refs/heads/main/broker-jaas-loginmodule.yaml
----

== 6. Validation and Testing
Verify that the security policies are correctly enforced by testing different user roles.

.Testing Admin Access (Success Expected)
[source,bash]
----
export POD=broker-prod-ss-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://samplequeue --user admin --password admin
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis consumer --acceptor all --destination queue://samplequeue --user admin --password admin
----

.Testing Viewer Access (Failure Expected)
The `batch` user belongs to the `viewer` role and should not have permissions to consume messages.
[source,bash]
----
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://samplequeue --user batch --password batch
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis consumer --acceptor all --destination queue://samplequeue --user batch --password batch
----

=== Expected Output for Viewer
When running the consumer as the `batch` user, you should see a security exception indicating that the JAAS module is correctly blocking unauthorized access:

[source,text]
----
javax.jms.JMSSecurityException: AMQ229213: User: batch does not have permission='CONSUME' for queue samplequeue on address samplequeue
----
