= Deploy and Secure Your AMQ Broker with KeyCloak 26: A Step-by-Step Guide

:toc: left
:toclevels: 3
:sectnums:

== Environment Setup

 - Red Hat Integration - AMQ Broker for RHEL 9 (Multiarch) : 7.13.2 provided by Red Hat

== Deploy and Configure KeyCloak 26 for AMQ Broker

This section covers setting up *KeyCloak* as an *OpenID Connect (OIDC)* provider.

=== Deploy KeyCloak 26

Create a new project and deploy the KeyCloak Operator.

[source, bash]
----
oc new-project keycloak
oc project keycloak
----

Deploy KeyCloak Subscription:

[source, bash]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhbk-operator.keycloak: ''
  name: rhbk-operator
  namespace: keycloak
spec:
  channel: stable-v26.2
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhbk-operator.v26.2.9-opr.1
EOF
----

Deploy Keycloak 26 Instance:

Create secret `example-tls-secret` required for the https exposed by the KeyCloak instance.
The `KEYCLOAK_HOST_URL` must be defined in the `CN=` in the following:

[source, bash]
----
openssl req -subj '/CN=keycloak-host.apps.abouchama-ai.emea.aws.cee.support/O=Keycloak-host/C=US' -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
oc create -n keycloak secret tls example-tls-secret --cert certificate.pem --key key.pem
----


[source, bash]
----
export KEYCLOAK_HOST_URL=keycloak-host.apps.abouchama-ai.emea.aws.cee.support
curl -sL https://raw.githubusercontent.com/aboucham/activemq-artemis-tutorials/refs/heads/main/keycloak/keycloak-install.yaml | \
envsubst | \
oc apply -n keycloak -f -
----

Retrieve the initial `admin` credentials:

[source, bash]
----
kubectl get secret -n keycloak example-kc-initial-admin -o jsonpath='{.data.username}' | base64 --decode
kubectl get secret -n keycloak example-kc-initial-admin -o jsonpath='{.data.password}' | base64 --decode
----

=== KeyCloak Configuration Steps

[source, bash]
----
oc apply -n keycloak -f https://raw.githubusercontent.com/aboucham/activemq-artemis-tutorials/refs/heads/main/keycloak/amq-broker-realm-KeycloakRealmImport.yaml
----

== Deploy AMQ Broker

=== Install AMQ Broker Operator

First, install the necessary Red Hat Operators for AMQ Broker into the `openshift-operators` namespace:

[source, bash]
----
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-broker-rhel9.openshift-operators: ""
  name: amq-broker-rhel9
  namespace: openshift-operators
spec:
  channel: 7.13.x
  installPlanApproval: Automatic
  name: amq-broker-rhel9
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-broker-operator.v7.13.1-opr-1-0.1756381365.p
EOF
----

=== Deploy AMQ Broker Secured by KeyCloak 26

1- To validate the RHBK server’s certificate by the AMQ Broker. The certificates of these remote server’s or the CA that signed these certificates must be put in a truststore and imported in a secret `keycloak-truststore`:

[source, bash,indent=0]
----
rm tls.crt
oc extract secret/example-tls-secret -n keycloak --confirm
oc create secret generic keycloak-truststore -n amq --from-file=tls.crt
----

2- Set up the right URL of the RHBK exposed on OpenShift in the keycloack json files:

[source, bash,indent=0]
----
export KEYCLOAK_URL=keycloak-sso.apps.com
cat <<EOF | envsubst > _keycloak-direct-access.json
{
  "realm": "amq-broker-realm",
  "auth-server-url": "https://\$KEYCLOAK_URL",
  "ssl-required": "all",
  "credentials": {
    "secret": "amq-broker-secret-value"
  },
  "resource": "amq-broker",
  "use-resource-role-mappings": true,
  "principal-attribute": "preferred_username",
  "verify-token-audience": true,
  "enable-basic-auth": true,
  "confidential-port": 0
}
EOF

cat <<EOF | envsubst > _keycloak-bearer-token.json
{
  "realm": "amq-broker-realm",
  "auth-server-url": "https://\$KEYCLOAK_URL",
  "ssl-required": "all",
  "resource": "amq-console",
  "public-client": true,
  "use-resource-role-mappings": true,
  "principal-attribute": "preferred_username",
  "verify-token-audience": false,
  "enable-basic-auth": true,
  "confidential-port": 0
}
EOF

cat <<EOF | envsubst > _keycloak-js-client.json
{
  "realm": "amq-broker-realm",
  "clientId": "amq-console",
  "url": "https://\$KEYCLOAK_URL"
}
EOF

cat <<"EOF" > login.config
console {
    // ensure the operator can connect to the broker by referencing the existing properties config
    org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
        org.apache.activemq.jaas.properties.user="artemis-users.properties"
        org.apache.activemq.jaas.properties.role="artemis-roles.properties"
        baseDir="/home/jboss/amq-broker/etc";

   org.keycloak.adapters.jaas.BearerTokenLoginModule sufficient
        keycloak-config-file="${secret.mount}/_keycloak-bearer-token.json"
        role-principal-class=org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal;

    org.apache.activemq.artemis.spi.core.security.jaas.PrincipalConversionLoginModule required
       principalClassList=org.keycloak.KeycloakPrincipal;
};
activemq {
    org.keycloak.adapters.jaas.BearerTokenLoginModule sufficient
        keycloak-config-file="${secret.mount}/_keycloak-bearer-token.json"
        role-principal-class=org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal;

    org.keycloak.adapters.jaas.DirectAccessGrantsLoginModule sufficient
        keycloak-config-file="${secret.mount}/_keycloak-direct-access.json"
        role-principal-class=org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal;

    org.apache.activemq.artemis.spi.core.security.jaas.PrincipalConversionLoginModule required
       principalClassList=org.keycloak.KeycloakPrincipal;
};
EOF
----

3- Use the oc create secret command to create a secret `keycloak-jaas-config` from the text file that you created with the new login module configuration. If the login module configuration includes a properties login module, also include the associated users and roles files in the secret. For example:

[source, bash,indent=0]
----
oc create secret -n amq generic keycloak-jaas-config --from-file=login.config --from-file=_keycloak-bearer-token.json --from-file=_keycloak-js-client.json --from-file=_keycloak-direct-access.json
----

[source, bash]
----
curl -sL https://raw.githubusercontent.com/aboucham/activemq-artemis-tutorials/refs/heads/main/activemqartemis-ex-aao-rhbk.yaml | \
envsubst | \
oc apply -n amq -f -
----
