= Federation in Action for AMQ Broker on OpenShift
We will dive deep into configuring, implementing, and optimizing ActiveMQ Artemis Broker Federation. In this hands-on demo, you'll learn how to set up federation between ActiveMQ Artemis brokers running on OpenShift, explore federation behavior in various scenarios, and discover best practices for ensuring fault tolerance and data redundancy in your messaging infrastructure.

== Chapters:

Environment Setup:

- Red Hat Integration - AMQ Broker for RHEL 8 (Multiarch) : 7.12.3-opr-1 provided by Red Hat

Prerequisites:

- Install AMQ Broker Operator:  from OperatorHub
- Generate certificates using keytool, create a secret for one way TLS: https://access.redhat.com/documentation/en-us/red_hat_amq_broker/7.11/html-single/deploying_amq_broker_on_openshift/index#proc-br-configuring-one-way-tls_broker-ocp[4.10.2.2. Configuring one-way TLS]

=== 1. Setting Up Initial Environment

- Production Env:

Create the 'production-east' namespace: `oc new-project production-east`

Create AMQ Broker using activemqArtemis CR YAML configuration

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
 name: broker-prod-east
 namespace: production-east
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
      protocols: all
      sslEnabled: false
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
      sslEnabled: false
  adminPassword: admin
  adminUser: admin
  brokerProperties:
    - maxDiskUsage=85
    - clusterConfigurations.my-cluster.producerWindowSize=-1
    - 'addressSettings.#.redeliveryMultiplier=5'
    - criticalAnalyzer=true
    - criticalAnalyzerTimeout=6000
    - criticalAnalyzerCheckPeriod=-1     
    - criticalAnalyzerPolicy=LOG
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: true
    clustered: true
    image: placeholder
EOF
----

- Production West Env:

Create the 'production-west' namespace: `oc new-project production-west`

Create AMQ Broker using activemqArtemis CR YAML configuration

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
 name: broker-prod-west
 namespace: production-west
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
      protocols: all
      sslEnabled: false
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
      sslEnabled: false
  adminPassword: admin
  adminUser: admin
  brokerProperties:
    - maxDiskUsage=85
    - clusterConfigurations.my-cluster.producerWindowSize=-1
    - 'addressSettings.#.redeliveryMultiplier=5'
    - criticalAnalyzer=true
    - criticalAnalyzerTimeout=6000
    - criticalAnalyzerCheckPeriod=-1     
    - criticalAnalyzerPolicy=LOG
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: true
    clustered: true
    image: placeholder
EOF
----

=== 2. Federation: amqp-federation-queue-dual-federation

Setup `Federation` using `brokerProperties` on the `broker-prod-east` broker:

`oc project production-east`

`broker-prod-east:`
[source, yaml,indent=0]
----
    - 'AMQPConnections.target.uri=tcp://broker-prod-west-all-0-svc.production-west.svc.cluster.local:61616'
    - AMQPConnections.target.user=admin
    - AMQPConnections.target.password=admin
    - AMQPConnections.target.autostart=true
    - AMQPConnections.target.federations.abc.type=FEDERATION
    - AMQPConnections.target.federations.abc.localQueuePolicies.policy1.includes.m4.queueMatch=tracking
    - addressConfigurations.tracking.queueConfigs.tracking.routingType=ANYCAST
----

`oc project production-west`
`broker-prod-west:`
[source, yaml,indent=0]
----
    - 'AMQPConnections.target.uri=tcp://broker-prod-east-all-0-svc.production-east.svc.cluster.local:61616'
    - AMQPConnections.target.user=admin
    - AMQPConnections.target.password=admin
    - AMQPConnections.target.autostart=true
    - AMQPConnections.target.federations.abc.type=FEDERATION
    - AMQPConnections.target.federations.abc.localQueuePolicies.policy1.includes.m4.queueMatch=tracking
    - addressConfigurations.tracking.queueConfigs.tracking.routingType=ANYCAST
----

In the logs of `broker-prod-east-ss-0` and `broker-prod-west-ss-0`  you should see the following lines:

[source, yaml,indent=0]
----
broker-prod-east-container AMQ601767: AMQP connection 4828734a for user unknown@broker-prod-west-all-0-svc.production-west.svc.cluster.local/172.30.181.112:61616 created
broker-prod-east-container AMQ111003:
broker-prod-east-container *******************************************************************************************************************************
broker-prod-east-container Connected on Server AMQP Connection target on broker-prod-west-all-0-svc.production-west.svc.cluster.local:61616 after 0 retries
*******************************************************************************************************************************
----

Following with lines for creating the queue `federation-control-link:abc:UUID` and a consumer assigned.

==== 2.1 Test :: Queue tracking :: Producer(broker-prod-east) --> Consumer(broker-prod-west)

[source, yaml,indent=0]
----
export POD=broker-prod-east-ss-0
oc exec -n production-east -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://tracking --user admin --password admin --message-count 1 --message 1
----

[source, yaml,indent=0]
----
export POD=broker-prod-west-ss-0
oc exec -n production-west -i $POD -- /home/jboss/amq-broker/bin/artemis consumer --acceptor all --destination queue://tracking --user admin --password admin --message-count 1
----

==== 2.2 Test :: Queue tracking :: Producer(broker-prod-west) --> Consumer(broker-prod-east)

[source, yaml,indent=0]
----
export POD=broker-prod-west-ss-0
oc exec -n production-west -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://tracking --user admin --password admin --message-count 1 --message 1
----

[source, yaml,indent=0]
----
export POD=broker-prod-east-ss-0
oc exec -n production-east -i $POD -- /home/jboss/amq-broker/bin/artemis consumer --acceptor all --destination queue://tracking --user admin --password admin --message-count 1
----


=== 3. Federation: amqp-federation local and remote

This will create a federation connection between servers, the local server will federate messages sent to the address 'orders' from the remote and the remote will federate message sent to the tracking queue on the local broker to itself.

-- orders from local (east) --> remote (west)
-- tracking from remote (west) --> local (east)

Setup `Federation` using `brokerProperties` on the `broker-prod-east` broker:

`oc project production-east`

`broker-prod-east:`
[source, yaml,indent=0]
----
    - addressConfigurations.tracking.queueConfigs.tracking.routingType=ANYCAST
    - addressConfigurations.orders.routingTypes=MULTICAST
    - addressConfigurations.orders.queueConfigs.orders.address=orders
    - addressConfigurations.orders.queueConfigs.orders.routingType=MULTICAST
    - 'AMQPConnections.target.uri=tcp://broker-prod-west-all-0-svc.production-west.svc.cluster.local:61616'
    - AMQPConnections.target.user=admin
    - AMQPConnections.target.password=admin
    - AMQPConnections.target.autostart=true
    - AMQPConnections.target.federations.abc.type=FEDERATION
    - AMQPConnections.target.federations.abc.localAddressPolicies.policy1.includes.m4.addressMatch=orders
    - AMQPConnections.target.federations.abc.remoteQueuePolicies.policy1.includes.m4.queueMatch=tracking
----

`oc project production-west`
No configuration should be added on the `broker-prod-west` CR.




=== 7. Configuring Federation

 Setup `Federation` using `brokerProperties` on the `broker-prod-east` broker:

`oc project production-east`

[source, yaml,indent=0]
----
    - 'AMQPConnections.target.uri=tcp://broker-prod-west-all-0-svc.production-west.svc.cluster.local:61616'
    - AMQPConnections.target.retryInterval=55
    - AMQPConnections.target.reconnectAttempts=-2
    - AMQPConnections.target.user=admin
    - AMQPConnections.target.password=admin
    - AMQPConnections.target.autostart=start
    - AMQPConnections.target.federations.abc.type=FEDERATION
    - AMQPConnections.target.federations.abc.localAddressPolicies.policy1.includes.m1.addressMatch=east.#
    - AMQPConnections.target.federations.abc.localAddressPolicies.policy1.excludes.m2.addressMatch=west.#
    - AMQPConnections.target.federations.abc.localAddressPolicies.policy1.maxHops=2
    - AMQPConnections.target.federations.abc.localAddressPolicies.policy1.autoDelete=true
    - AMQPConnections.target.federations.abc.localAddressPolicies.policy1.autoDeleteMessageCount=42
    - AMQPConnections.target.federations.abc.localAddressPolicies.policy1.autoDeleteDelay=10000
    - AMQPConnections.target.federations.abc.localQueuePolicies.policy2.includes.m4.queueMatch=#
    - AMQPConnections.target.federations.abc.localQueuePolicies.policy2.excludes.m5.queueMatch=west.#
    - AMQPConnections.target.federations.abc.remoteAddressPolicies.policy3.includes.m1.addressMatch=west.#
    - AMQPConnections.target.federations.abc.remoteAddressPolicies.policy3.excludes.m2.addressMatch=east.#
    - AMQPConnections.target.federations.abc.remoteQueuePolicies.policy4.includes.m4.queueMatch=#
    - AMQPConnections.target.federations.abc.remoteQueuePolicies.policy4.excludes.m5.queueMatch=east.#
----

In the logs of `broker-prod-east-ss-0` you should see the following lines:

[source, yaml,indent=0]
----
broker-prod-east-container AMQ601767: AMQP connection 4828734a for user unknown@broker-prod-west-all-0-svc.production-west.svc.cluster.local/172.30.181.112:61616 created
broker-prod-east-container AMQ111003:
broker-prod-east-container *******************************************************************************************************************************
broker-prod-east-container Connected on Server AMQP Connection target on broker-prod-west-all-0-svc.production-west.svc.cluster.local:61616 after 0 retries
*******************************************************************************************************************************
----

In the list of addresses and queues, you should see the following:

`federation-control-link:abc:UUID`
`federation-events-sender:abc:UUID`

[source, yaml,indent=0]
----
export POD=broker-prod-east-ss-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis address show --acceptor all --user admin --password admin
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis queue stat --acceptor all --user admin --password admin
----
[source, yaml,indent=0]
----
export POD=broker-prod-west-ss-0
oc exec -n production-west -i $POD -- /home/jboss/amq-broker/bin/artemis address show --acceptor all --user admin --password admin
oc exec -n production-west -i $POD -- /home/jboss/amq-broker/bin/artemis queue stat --acceptor all --user admin --password admin
----

[source, yaml,indent=0]
----
export POD=broker-prod-east-ss-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://JOBS --user admin --password admin --message-count 1 --message 1
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://JOBS --user admin --password admin --message-count 1 --message 2
----

=== 7. Deep Dive::

https://github.com/apache/activemq-artemis-examples/tree/main/examples/features/broker-connection

Core Federeation:

[source, yaml,indent=0]
----
  brokerProperties:
  - globalMaxSize=1GiB
  - clusterConfigurations.my-cluster.messageLoadBalancingType=ON_DEMAND
  - connectorConfigurations.ns1-federation-connector.params.host=artemis-broker-core-tls-0-svc-rte-ns1.apps.cluster-zz9jt.zz9jt.sandbox2715.opentlc.com
  - connectorConfigurations.ns1-federation-connector.params.port=443
  - connectorConfigurations.ns1-federation-connector.params.sslEnabled=true
  - connectorConfigurations.ns1-federation-connector.params.trustStorePath=/etc/artemis-broker-tls-secret-volume/client.ts
  - connectorConfigurations.ns1-federation-connector.params.trustStorePassword=password
  - federationConfigurations.ns2-to-ns1.credentials.user=master
  - federationConfigurations.ns2-to-ns1.credentials.password=master
  - federationConfigurations.ns2-to-ns1.upstreamConfigurations.ns1.connectionConfiguration.staticConnectors=ns1-federation-connector
  - federationConfigurations.ns2-to-ns1.upstreamConfigurations.ns1.connectionConfiguration.retryInterval=500
  - federationConfigurations.ns2-to-ns1.upstreamConfigurations.ns1.connectionConfiguration.retryIntervalMultiplier=2
  - federationConfigurations.ns2-to-ns1.upstreamConfigurations.ns1.connectionConfiguration.maxRetryInterval=30000
  - federationConfigurations.ns2-to-ns1.upstreamConfigurations.ns1.connectionConfiguration.circuitBreakerTimeout=30000
  - federationConfigurations.ns2-to-ns1.upstreamConfigurations.ns1.connectionConfiguration.shareConnection=true
  - federationConfigurations.ns2-to-ns1.upstreamConfigurations.ns1.policyRefs=app-qp
  - federationConfigurations.ns2-to-ns1.queuePolicies.app-qp.includeFederated=false
  - federationConfigurations.ns2-to-ns1.queuePolicies.app-qp.includes.all-app.queueMatch=app.#
----

[source, yaml,indent=0]
----
  brokerProperties:
  - globalMaxSize=1GiB
  - clusterConfigurations.my-cluster.messageLoadBalancingType=ON_DEMAND
  - connectorConfigurations.ns2-federation-connector.params.host=artemis-broker-core-tls-0-svc-rte-ns2.apps.cluster-vqs45.vqs45.sandbox3224.opentlc.com
  - connectorConfigurations.ns2-federation-connector.params.port=443
  - connectorConfigurations.ns2-federation-connector.params.sslEnabled=true
  - connectorConfigurations.ns2-federation-connector.params.trustStorePath=/etc/artemis-broker-tls-secret-volume/client.ts
  - connectorConfigurations.ns2-federation-connector.params.trustStorePassword=password
  - federationConfigurations.ns1-to-ns2.credentials.user=master
  - federationConfigurations.ns1-to-ns2.credentials.password=master
  - federationConfigurations.ns1-to-ns2.upstreamConfigurations.ns2.connectionConfiguration.staticConnectors=ns2-federation-connector
  - federationConfigurations.ns1-to-ns2.upstreamConfigurations.ns2.connectionConfiguration.retryInterval=500
  - federationConfigurations.ns1-to-ns2.upstreamConfigurations.ns2.connectionConfiguration.retryIntervalMultiplier=2
  - federationConfigurations.ns1-to-ns2.upstreamConfigurations.ns2.connectionConfiguration.maxRetryInterval=1000
  - federationConfigurations.ns1-to-ns2.upstreamConfigurations.ns2.connectionConfiguration.circuitBreakerTimeout=1000
  - federationConfigurations.ns1-to-ns2.upstreamConfigurations.ns2.connectionConfiguration.shareConnection=true
  - federationConfigurations.ns1-to-ns2.upstreamConfigurations.ns2.policyRefs=app-qp
  - federationConfigurations.ns1-to-ns2.queuePolicies.app-qp.includeFederated=false
  - federationConfigurations.ns1-to-ns2.queuePolicies.app-qp.includes.all-app.queueMatch=app.#
----


**NOTE:** the amqp federation is the way to go, it it intentionally similar to the core federation but better and in active dev. we really should be deprecating core federation.
the issue of no logging etc when it does not work and debugging.... those are the sort of things that are better in the amqp federation. and any short coming in amqp federation will be a priority.

Source: https://github.com/apache/activemq-artemis/blob/9583f844c17ff3463327f5e0ae209ef10c[…]he/activemq/artemis/core/config/impl/ConfigurationImplTest.java

==== 7.2 Custom Logging for troubleshooting:

Enable specific `logging` for troubleshooting on the broker with mirroring configuration:

Create configmap with custom logging:

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-logging-config
data:
  logging.properties: |2
    appender.stdout.name = STDOUT
    appender.stdout.type = Console
    rootLogger = info, STDOUT
    logger.activemq.name=org.apache.activemq.artemis.core.config.impl.ConfigurationImpl
    logger.activemq.level=TRACE
    logger.jaas.name=org.apache.activemq.artemis.spi.core.security.jaas
    logger.jaas.level=TRACE
    logger.rest.name=org.apache.activemq.artemis.core
    logger.rest.level=ERROR
EOF
----

Mount the configmap to the activemqArtemis level:

[source, yaml,indent=0]
----
    extraMounts:
      configMaps:
        - custom-logging-config
----
