= Mirroring in Action for AMQ Broker on OpenShift
We will dive deep into configuring, implementing, and optimizing ActiveMQ Artemis Broker Mirroring. In this hands-on demo, you'll learn how to set up mirroring between ActiveMQ Artemis brokers running on OpenShift, explore mirroring behavior in various scenarios, and discover best practices for ensuring fault tolerance and data redundancy in your messaging infrastructure.

== Chapters:

Environment Setup:

- Red Hat Integration - AMQ Broker for RHEL 8 (Multiarch) : 7.11.6-opr-2 provided by Red Hat

Prerequisites:

- Install AMQ Broker Operator:  from OperatorHub
- Generate certificates using keytool, create a secret for one way TLS: https://access.redhat.com/documentation/en-us/red_hat_amq_broker/7.11/html-single/deploying_amq_broker_on_openshift/index#proc-br-configuring-one-way-tls_broker-ocp[4.10.2.2. Configuring one-way TLS]

=== 2. Setting Up Initial Environment

- Production Env:

Create the 'production' namespace: `oc new-project production`

Create AMQ Broker using activemqArtemis CR YAML configuration

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
 name: broker-prod
 namespace: production
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
      protocols: all
      sslEnabled: false
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
      sslEnabled: false
  adminPassword: admin
  adminUser: admin
  brokerProperties:
    - maxDiskUsage=85
    - clusterConfigurations.my-cluster.producerWindowSize=-1
    - 'addressSettings.#.redeliveryMultiplier=5'
    - criticalAnalyzer=true
    - criticalAnalyzerTimeout=6000
    - criticalAnalyzerCheckPeriod=-1     
    - criticalAnalyzerPolicy=LOG
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: true
    clustered: true
    image: placeholder
EOF
----

- DR Env:

Create the 'DR' namespace: `oc new-project dr`

Create AMQ Broker using activemqArtemis CR YAML configuration

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
 name: broker-dr
 namespace: dr
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
      protocols: all
      sslEnabled: false
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
      sslEnabled: false
  adminPassword: admin
  adminUser: admin
  brokerProperties:
    - maxDiskUsage=85
    - clusterConfigurations.my-cluster.producerWindowSize=-1
    - 'addressSettings.#.redeliveryMultiplier=5'
    - criticalAnalyzer=true
    - criticalAnalyzerTimeout=6000
    - criticalAnalyzerCheckPeriod=-1     
    - criticalAnalyzerPolicy=LOG
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: true
    clustered: true
    image: placeholder
EOF
----

=== 3. Configuring Mirroring and Understanding Pre-existing Messages

`oc project production`

We will create `queue A` and send `3 messages` before establishing `Mirroring Connections`:

[source, yaml,indent=0]
----
export POD=broker-prod-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://A --user admin --password admin --message-count 1 --message 1 
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://A --user admin --password admin --message-count 1 --message 2
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://A --user admin --password admin --message-count 1 --message 3
----


 Setup `Mirroring` using `brokerProperties` on the `broker-prod` broker:

[source, yaml,indent=0]
----
    - >-
      AMQPConnections.target.uri=tcp://target-broker-all-0-svc.dr.svc.cluster.local:61616
    - AMQPConnections.target.retryInterval=5000
    - AMQPConnections.target.user=admin
    - AMQPConnections.target.password=admin
    - AMQPConnections.target.connectionElements.mirror.type=MIRROR
    - >-
      AMQPConnections.target.connectionElements.mirror.messageAcknowledgements=true
    - AMQPConnections.target.connectionElements.mirror.queueCreation=true
    - AMQPConnections.target.connectionElements.mirror.queueRemoval=true
----

[source, yaml,indent=0]
----
oc apply -f https://raw.githubusercontent.com/aboucham/activemq-artemis-tutorials/main/broker-prod-mirroring.yaml
----

Check the address/queue `A` created without 3 messages.

--> Pre Existing Messages
The broker will only mirror messages arriving from the point in time the mirror was configured. 
Previously existing messages will not be forwarded to other brokers.


=== 4. Mirroring in a Scale-Up Scenario

Update Mirroring uri configuration by using the env variable `${STATEFUL_SET_ORDINAL}` , this env var provide sequential identities for pod replicas, and when using OrderedReady Pod management, Pods are created from ordinal index 0 up to N-1.

[source, yaml,indent=0]
----
    - >-
      AMQPConnections.target.uri=tcp://target-broker-all-${STATEFUL_SET_ORDINAL}-svc.dr.svc.cluster.local:61616
    - AMQPConnections.target.retryInterval=5000
    - AMQPConnections.target.user=admin
    - AMQPConnections.target.password=admin
    - AMQPConnections.target.connectionElements.mirror.type=MIRROR
    - >-
      AMQPConnections.target.connectionElements.mirror.messageAcknowledgements=true
    - AMQPConnections.target.connectionElements.mirror.queueCreation=true
    - AMQPConnections.target.connectionElements.mirror.queueRemoval=true
----

Then, change the replicas on the DR env (mirrored env), then on the production env:

[source, yaml,indent=0]
----
kubectl -n dr scale ActiveMQArtemis broker-dr --replicas 2
kubectl -n production scale ActiveMQArtemis broker-dr --replicas 2
----

=== 5. Exploring Address Filtering

Update Mirroring uri configuration by using the addressFilter.
AdressFilter is An optional comma-separated list of `inclusion and/or exclusion` filter entries used to govern which addresses (and related queues) mirroring events will be created for on this broker-connection.

For instance: `addressFilter=fr.,!eu.` allow to include/mirror only adresses/queues that starts with `fr.` and excluse all the adresses/queues that starts with `eu.`

[source, yaml,indent=0]
----
    - >-
      AMQPConnections.target.uri=tcp://target-broker-all-${STATEFUL_SET_ORDINAL}-svc.dr.svc.cluster.local:61616
    - AMQPConnections.target.retryInterval=5000
    - AMQPConnections.target.user=admin
    - AMQPConnections.target.password=admin
    - AMQPConnections.target.connectionElements.mirror.type=MIRROR
    - >-
      AMQPConnections.target.connectionElements.mirror.messageAcknowledgements=true
    - AMQPConnections.target.connectionElements.mirror.queueCreation=true
    - AMQPConnections.target.connectionElements.mirror.queueRemoval=true
    - 'AMQPConnections.target.connectionElements.mirror.addressFilter=fr.,!eu.'
----


=== 6. Troubleshooting Mirroring

Event: Creating Address:

[source, yaml,indent=0]
----
export POD=broker-prod-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis address create --name A --address A --user admin --password admin --acceptor all
----

Event: Creating Queue:

[source, yaml,indent=0]
----
export POD=broker-prod-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis queue create --name A --address A --user admin --password admin --acceptor all
----

Event Producing Messages:

[source, yaml,indent=0]
----
export POD=broker-prod-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis producer --acceptor all --destination queue://A --user admin --password admin --message-count 1 --message 1 
----

The above broker properties would create two address testQueue and testTopic.
With command

[source, yaml,indent=0]
----
export POD=broker-prod-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis queue stat --acceptor all --user admin --password admin
----
excuted on the pod it is possible to display the created ANYCAST queue and confirm that it has been created. To confirm that a MULTICAST address has been created use command

[source, yaml,indent=0]
----
export POD=broker-prod-0
oc exec -i $POD -- /home/jboss/amq-broker/bin/artemis address show --acceptor all --user admin --password admin
----

Enable specific logging to troubleshoot:

Create configmap with custom logging:

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-logging-config
data:
  logging.properties: |2
    appender.stdout.name = STDOUT
    appender.stdout.type = Console
    rootLogger = info, STDOUT
    logger.activemq.name=org.apache.activemq.artemis.core.config.impl.ConfigurationImpl
    logger.activemq.level=TRACE
    logger.jaas.name=org.apache.activemq.artemis.spi.core.security.jaas
    logger.jaas.level=TRACE
    logger.rest.name=org.apache.activemq.artemis.core
    logger.rest.level=ERROR
EOF
----

Mount the configmap to the activemqArtemis level:

[source, yaml,indent=0]
----
    extraMounts:
      configMaps:
        - custom-logging-config
----


